[package]
name = "token"
version = "0.1.0"
edition = "2024_07"

[dependencies]
garaga = { git = "https://github.com/keep-starknet-strange/garaga.git", tag = "v0.17.0" }
starknet = "2.11.4"
mint = { path = "../mint/cairo" }
transfer = { path = "../transfer/cairo" }
burn = { path = "../burn/cairo" }

[dev-dependencies]
snforge_std = "0.40.0"
assert_macros = "2.8.4"

[[target.starknet-contract]]
sierra = true
allowed-libfuncs-list.name = "audited"
build-external-contracts = ["mint::mint_verifier::MintVerifier", "transfer::transfer_verifier::TransferVerifier", "burn::burn_verifier::BurnVerifier"]

[scripts]
test = "snforge test"
deploy-test = "bash ./scripts/deploy-test.sh"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[lib]
